### ISSUE TITLE
Unable to split client and server

### ISSUE THREAD

**Issue by aaronhuisinga** [JulianMar/nuxt-bugsnag#10]
As noted in the readme, Bugsnag recommends using different apps for the client and server side. However, I cannot figure out how to actually use two separate API keys using this package. I see the module references both a config and clientConfig, but early on in the file everything in the clientConfig is overwritten by the config.

With this, I don't see a possible way to pass a separate API key for the client and server. Am I missing something simple here? The readme mentions this as well, but doesn't provide an example for how it actually functions.

**Comment by JulianMar** [comment]
Hi, 

I am sad to inform you but this feature got removed. In my usecase it didn't fit well. As for the documentation, it is outdated. 

I will update the docs! Thanks
