### ISSUE TITLE
no source control info found

### ISSUE THREAD

**Issue by simplenotezy** [JulianMar/nuxt-bugsnag#11]
When running my build I get this warning:

```
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/5ca9883b991adbce19fc.js"                                                                                                              14:46:21
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/f39f9977b1b29df7487a.js"                                                                                                              14:46:21
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/b594074f4f5007402ad2.js"                                                                                                              14:46:21
[bugsnag-build-reporter] no source control info found (looked in package.json, .git, .hg)
```

Any idea why, or how I can add source control info?

**Comment by JulianMar** [comment]
Hi, is you project a git project? 
If yes it should automatically detect everything for you

**Comment by simplenotezy** [comment]
Hey @JulianMar - apologies for my slow response. Yes it is indeed a git project, and I have git both on the server and locally.

**Comment by JulianMar** [comment]
Okay weird. Is there an output for these 3 commands? If you don't use the origin remote that could lead to problems
```
git rev-parse HEAD
git remote get-url origin
git remote -v
```

If not you can manually add this data in the package.json
```
"repository": {
	"url": "your repo url"
}
```

While digging through the source code of the plugin I noticed that if you use a git on premise solution it won't work either. I will update the library so this data can be passed throug aswell

**Comment by simplenotezy** [comment]
@JulianMar All your commands outputted references to our git. I'll keep an eye if the bug appears again on next deploy

**Comment by simplenotezy** [comment]
Yeah looking through deploy hooks, the error does still appear:

    [bugsnag-build-reporter] no source control info found (looked in package.json, .git, .hg)

**Comment by JulianMar** [comment]
I created a PR #13 for this issue, but it seems like nuxt-edge has a issue right now.
I will try again after the weekend to check if the build succeeds.

For now you can check out the docs in the PR

**Comment by simplenotezy** [comment]
Great @JulianMar - I will test it out. Seems like nuxt has a lot of issues at the moment.
