### ISSUE TITLE
No @bugsnag/plugin-vue installed

### ISSUE THREAD

**Issue by Triloworld** [JulianMar/nuxt-bugsnag#15]
Add as dependency for website - maybe note? or it can be somehow automated?
It is in package but isn't picked up by plugin import
Source of problem: https://github.com/JulianMar/nuxt-bugsnag/blob/29cc40ba99eb951f03f73aa7107ff07ea999f53a/lib/plugin.js#L3

I get this from module after installing myself:
[bugsnag] Bugsnag.start() was called more than once. Ignoring.     

Versions:
    "npm": "^6.14.5",
    "vue": "^2.6.11",
    "nuxt": "^2.12.2",
    "nuxt-bugsnag": "^4.1.0",
    "webpack": "^4.43.0",
    "webpack-dev-server": "^3.11.0"

**Comment by Triloworld** [comment]
Ok, propably somehow releated: https://www.npmjs.com/package/@bugsnag/plugin-vue#usage

```
const Vue = require('vue')
const Bugsnag = require('@bugsnag/js')
const bugsnagVue = require('@bugsnag/plugin-vue')
 
Bugsnag.start('API_KEY')
Bugsnag.use(bugsnagVue, Vue)
```

They use as a example "Bugsnag.use("
In repo is maybe older version of importing it:
```
const options = <%= serialize(options) %>
options.plugins = [new BugsnagPluginVue(Vue)]
const bugsnagClient = Bugsnag.start(options)
```

**Comment by JulianMar** [comment]
Hi, so the plugin is installing correctly, you don't need to add the `@bugsnag` dependencies.

The was called more than once error is okay. It doesn't change the behaviour.

But after checking the docs I found that something is missing. After calling init you should do `installVueErrorHandler(vue)` like mentioned here https://docs.bugsnag.com/platforms/javascript/vue/.

After checking the example for nuxt.js from [bugsnag](https://github.com/bugsnag/bugsnag-js/blob/next/examples/js/nuxtjs/modules/bugsnag/client.js) they are themselves making this error.

**Comment by Triloworld** [comment]
I check this: https://docs.bugsnag.com/platforms/javascript/vue/
Propably in wrong place.

```
Bugsnag.start({
  apiKey: 'YOUR_API_KEY',
  plugins: [new BugsnagPluginVue()],
  otherOptions: value
})
```

**Comment by JulianMar** [comment]
check out this one
https://github.com/bugsnag/bugsnag-js/blob/master/UPGRADING.md
I forgot to follow the upgrade guide

**Comment by Triloworld** [comment]
Yeah! I see what you mention :)

**Comment by JulianMar** [comment]
I think PR #16 should fix both problems. I will test locally first

**Comment by JulianMar** [comment]
After looking through the source code of the bugsnag-vue plugin I noticed they are using the window object in there 🤦‍♂️ So no SSR support for that version, I will not change the syntax of the init yet. 

But I have opened a issue with bugsnag [here](https://github.com/bugsnag/bugsnag-js/issues/895)

**Comment by Triloworld** [comment]
Yep I tested and found that in context of mobile it work (before export occur is placed). 
Thanks once more for help :)

**Comment by JulianMar** [comment]
Yes, just found out aswell! 

So I check the CI and will release a bugfix version after that :)

Thanks for the report

**Comment by JulianMar** [comment]
It live!
