### ISSUE TITLE
[bugsnag] Bugsnag.start() was called more than once. Ignoring.

### ISSUE THREAD

**Issue by gizburdt** [JulianMar/nuxt-bugsnag#17]
I get this warning multiple times when nuxt is started. This error will be pushed to bugsnag.

Is this something you can reproduce? Or am I doing something wrong?

nuxt.config
```
modules: [
    ...
    'nuxt-bugsnag',
    ...
]

...

bugsnag: {
    apiKey: process.env.BUGSNAG_API_KEY
},
```

**Comment by JulianMar** [comment]
Which Version of the library do you use? 
And what does your package.json look like?

As far as I know this bug was solved with the 4.1 release

**Comment by gizburdt** [comment]
Thanks for the quick reply! :)

This is in my package.json: `"nuxt-bugsnag": "^4.1.1",`

**Comment by JulianMar** [comment]
okay, that's right.
Can you try deleting your node_modules and reinstalling them?

**Comment by gizburdt** [comment]
Didn't fix it unfortunately :(

**Comment by JulianMar** [comment]
okay I will try to recreate it on my local env and get back to you

**Comment by gizburdt** [comment]
Awesome! :)

**Comment by JulianMar** [comment]
I just released a new version. Can you check it out?
Would be nice to know if it works for everyone :)

**Comment by gizburdt** [comment]
Looks like it's working! Thanks for the quick fix :)

If I find something else, I will let you know

**Comment by JulianMar** [comment]
Nice, thanks for your patience and if you find something please let me know :)
