### ISSUE TITLE
Include bugsnag library manually

### ISSUE THREAD

**Issue by simplenotezy** [JulianMar/nuxt-bugsnag#19]
Is there a way to include the library manually? I'd like to only initiate the bugsnag environment through their official CDN and only on certain conditions; say after 5 seconds (to help increase PageSpeed score) or once a visitor interacts in any way with the site; say moves mouse or scrolls.

I'm not sure how this would be done. I could just "ditch" the library and then include myself, but then I would miss:

- Publish release source-maps
- Error reporting during build of static site
- Version

Would be great to have some looks on this. An even more advanced technique would be to capture any JS error in a global variable, and should JS errors happen before Bugsnag was initialised, then these are sent manually once script has loaded. Kinda like Google Tag Manager.

**Comment by JulianMar** [comment]
You have some nice ideas. But it makes more sense to include them upstream in the Bugsnag js library.
Especially the buffering of the Errors. But that won't work without code already included.

Currently there is no way to use the CDN version of Bugsnag.
