### ISSUE TITLE
beforeSend() configuration option does not work

### ISSUE THREAD

**Issue by mikkokut** [JulianMar/nuxt-bugsnag#2]
It seems that the beforeSend() configuration option does not work. Should it work?

**Comment by JulianMar** [comment]
yeah true, due to the JSON.stringify all functions get stripped from the object
I will check for a workaround

**Comment by JulianMar** [comment]
I solved it by using `serialize` instead of `JSON.stringify`. See #3 
But be aware that something like `console.log` in your beforeSend won't work due webpack compilation. if you use `window.console.log` instead it will work!

**Comment by mikkokut** [comment]
Thanks a lot!

**Comment by JulianMar** [comment]
New version tagged at 2.0.4 
Thanks for using it :)
