### ISSUE TITLE
Difference between options in "config" or not

### ISSUE THREAD

**Issue by simplenotezy** [JulianMar/nuxt-bugsnag#23]
Reading the [documentation](https://github.com/JulianMar/nuxt-bugsnag#setup), it's a little bit confusing what's the difference between 

`{
  modules: [
    ['nuxt-bugsnag', {
      apiKey: 'Your_API_KEY'
    }]
  ]
}`

and

`{
  modules: [
    ['nuxt-bugsnag', {
      config: {
        apiKey: 'YOUR_BROWSER_API_KEY'
      },
    }]
  ]
}`

Also to seperate bugsnag environments, I've done it this way: `(process.client) ? process.env.BUGSNAG_API_KEY : process.env.BUGSNAG_SERVER_API_KEY`. Is there a plugin specific way to do this, or is my approach fine?

**Comment by JulianMar** [comment]
Yes you are definitly right. The docs are not good.  

The config object is for passing data to Bugsnag directly. You can define everything mentioned in here https://docs.bugsnag.com/platforms/javascript/configuration-options/  

There is no wrong or right way to do it. I personally just set my apiKey. Bugsnag will check `NODE_ENV` and add the `local`, `dev` or `production` tag to the error reported.

Your approach is fine but you need two Bugsnag Projects

**Comment by LTDanwithlegs** [comment]
@simplenotezy, for secrets, API keys, and environment strings, an untracked `.env` is a good practice. However, unless you use something like a Parameter Store (AWS), it can get tricky keeping your teams' `.env` files up to date. Our teams go this route and ensure that our builds pull the `.env` dynamically from the Parameter Store.

So for your example, specifically, you could have a local Store, a staging Store, and a production Store. You config file would only look at `process.env.BUGSNAG_API_KEY`, and each of the Stores could have a different value for that env variable. Your build pipeline would determine which Store gets used.

But, @JulianMar is right, you'd need multiple Bugsnag projects. You may want to take a look at having the API Key be the same for all environments, and just specify the environment name in the config - that part can and should be different in each of the build environments. That way, you can track staging bugs separately from production bugs, and even disregard local ones (there are usually a lot of those. haha)

**Comment by simplenotezy** [comment]
Thanks for your inputs, everybody. I have tried with this setup:

		[ 'nuxt-bugsnag', {
			apiKey: (process.client) ? process.env.BUGSNAG_API_KEY : process.env.BUGSNAG_SERVER_API_KEY,
			reporterOptions: {
				releaseStage: process.env.ENVIRONMENT || 'local',
				autoAssignRelease: true
			},
			publishRelease: (process.env.ENVIRONMENT !== 'local'),
			notifyReleaseStages: [ 'staging', 'production' ],
			enabledReleaseStages: [ 'staging', 'production' ]
		} ],

However, I find that on my client, if an error happens, it uses the SERVER_API_KEY. I use nuxt with Server Side Rendering. So not sure what's wrong here.

**Comment by LTDanwithlegs** [comment]
If you take a look at the [Nuxt lifecycle](https://nuxtjs.org/docs/2.x/concepts/nuxt-lifecycle/), it makes sense that `process.env.BUGSNAG_SERVER_API_KEY` is always being used, since `(process.client)` - when in SSR or universal mode - will always be false on init.

Why is it that you want them separate? I don't think I understand that context of your problem. We run ours with just a single `BUGSNAG_API_KEY` (for context, we also use universal mode).

**Comment by JulianMar** [comment]
Yes @LTDanwithlegs is perfectly right. The API_KEY will be pushed into the plugin on compile time, so it will be always the `BUGSNAG_SERVER_API_KEY`.  
If you provide your use case we can help you solve it! For my Use case one `API_KEY` is enough

**Comment by simplenotezy** [comment]
> If you take a look at the [Nuxt lifecycle](https://nuxtjs.org/docs/2.x/concepts/nuxt-lifecycle/), it makes sense that `process.env.BUGSNAG_SERVER_API_KEY` is always being used, since `(process.client)` - when in SSR or universal mode - will always be false on init.
> 
> Why is it that you want them separate? I don't think I understand that context of your problem. We run ours with just a single `BUGSNAG_API_KEY` (for context, we also use universal mode).

@LTDanwithlegs Simply to keep server side rendering issues separate from frontend issues, I guess both cases work just fine

@JulianMar You're absolutely right

**Comment by LTDanwithlegs** [comment]
@simplenotezy, the Bugsnag API allows you to tag bugs and console errors with custom metadata via the `metadata` prop. For example, one of our systems is a Nuxt rendering engine for headless content. This system is used by multiple brands and multiple affiliates. We store the active brand and affiliate in the data store (not the AWS Parameter Store), and grab those values when a bug happens. So from one account, we can see if certain affiliates are trying to do something with one of our brands that is causing more bugs than others.

Something like that might help solve your issue and make it so you only have to use one account.

**Comment by LTDanwithlegs** [comment]
Here's the [Bugsnag doc](https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#global-metadata) on custom metadata I was referencing. Global seems like it would work for your case (since the variable would be present for every bug), but you can also send metadata custom for different types of events.
