### ISSUE TITLE
Source maps not working with Nuxt 2.15

### ISSUE THREAD

**Issue by Matiyeu** [JulianMar/nuxt-bugsnag#25]
I get an infinite loop on the source maps upload when I do the build with `nuxt build`

     {
        apiKey: process.env.BUGSNAG_APIKEY,
        publishRelease: true,
        reporterOptions: {
          appVersion: pkg.version,
          releaseStage: process.env.MODE, <= 'production'
          enabledReleaseStages: ['staging', 'production'],
          autoAssignRelease: true,
        }
      }

nuxt: `2.15.4`
nuxt-bugsnag: `4.2.2`

**Comment by JulianMar** [comment]
Hmm weird issue. Can you maybe try to change from `reporterOptions` to `config`.  
looks like not every option you pass is valid for the options object. [Here](https://github.com/bugsnag/webpack-bugsnag-plugins#new-bugsnagbuildreporterpluginbuild-optswebpackplugin) is a list of option.  
In particular I think the enabledReleaseStages, is causing problems.

Would be very cool if you can attach a working reproduction of the issue!

**Comment by Matiyeu** [comment]
It works with version 2.14 of Nuxt. 
The enabledReleaseStages variable is staging or production as in the doc

**Comment by JulianMar** [comment]
Did you try changing to config?

**Comment by Matiyeu** [comment]
Yes it does not work

**Comment by JulianMar** [comment]
I used your config and it works for me.
Do you see some logs like this:
```
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/517df50.js"                                                                                                                                                                        18:14:07
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/a75f891.js"                                                                                                                                                                        18:14:07
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/cbb6e43.js"                                                                                                                                                                        18:14:07
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/fb566a3.js"                                                                                                                                                                        18:14:07
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/729ae27.js"                                                                                                                                                                        18:14:07
[BugsnagSourceMapUploaderPlugin] uploading sourcemap for "*/56515c8.js"     
```

**Comment by Matiyeu** [comment]
Yes infinite log like that

**Comment by JulianMar** [comment]
Check your bugsnag project settings and source maps, are they in there?
If yes it is working

**Comment by Matiyeu** [comment]
I can't, the build never ends...

**Comment by JulianMar** [comment]
Okay, do you maybe use corejs 2?  
If not can you try `DEBUG=nuxt:* yarn build` and check the output maybe you see some errors

**Comment by JulianMar** [comment]
or can you paste your `nuxt.config.js` file
