### ISSUE TITLE
Problem with CORS after initial load

### ISSUE THREAD

**Issue by rudolfbruder** [JulianMar/nuxt-bugsnag#26]
Hi, 

I am trying to use this package with my laravel nuxt project which is SSR. On initial page load which comes from server the errors are being send and appear on the bugsnag report however once the 'SPA' mode turns in the app is unable to send the request to bugsnag with the typical cors error, see picture:

![image](https://user-images.githubusercontent.com/56951790/126266209-9c49668d-2a02-4234-bd77-3402b3454a42.png)

I was think whether this has something to do with axios setup but it seems it does not because it actually does not use nuxt axios module because it does not incl due headers which i specified during the axios setup.

I am sure it is because it is missing the headers in the request here:

![image](https://user-images.githubusercontent.com/56951790/126266300-4981f89b-a85b-4c1f-aa6f-5940659cd637.png)

Do you have any idea how could I solve this issue please?

Thank you very much!

**Comment by JulianMar** [comment]
Hey,
hmm this is very weird. As far as I can tell it has nothing to do with the library. 

But I can try to help you work through this problem. 
So basically it uses the [bugsnag js](https://github.com/bugsnag/bugsnag-js) library, where I didn't find any issues related to your Problem.
Do you maybe have a reproducable version?

**Comment by rudolfbruder** [comment]
Hello,

You know what I have discovered this weekend, the problem exists only in Firefox. In google Chrome the CORS error is not present. I have no idea why it is happening in firefox only. Pity that I am so used to firefox.

**Comment by JulianMar** [comment]
ohh wow, you are right.
This is maybe a bigger issue. I will try to find out more

**Comment by JulianMar** [comment]
scrape that 🤦🏼 . I had ublock origin activated. For me it works on firefox

**Comment by rudolfbruder** [comment]
It's interesting because I have an Laravel / Nuxt.js application with SSR. On the first page load when the page is server from the server the bugsnag runs through. I guess because it is handled by the laravel cors settings. Then when it's handle by the front end it is not using the axios setup but it's own request setup i guess which ignores my headers.

**Comment by JulianMar** [comment]
but why do you do you need special settings? Do you a proxy or something like that setup for your bugsnag requests? Can you maybe share your nuxt.config?

Another question would be, do you use laravel as API? Like maybe the laravel-nuxt project?

**Comment by rudolfbruder** [comment]
@JulianMar you solved it. I did not have ublock but some other adblock called AdBlocker Ultimate. I disabled it and it works now. Thank you very much! Hope this helps other people with adblock enabled.

**Comment by JulianMar** [comment]
awesome! But weird that on Firefox it's a cors error, when it's blocking the requests
