### ISSUE TITLE
Cannot find module nuxt-bugsnag/dist/module.cjs when trying to install

### ISSUE THREAD

**Issue by dritter** [JulianMar/nuxt-bugsnag#32]
Hi Julian,

when trying to install this repo after a fresh clone, I get the following error:

![image](https://user-images.githubusercontent.com/1544760/181024871-5ccb7ca7-7c8f-4f18-900d-46f23d638d2b.png)

I use `node` v18.6.0 and `npm` 8.15.0 on Linux.

**Comment by JulianMar** [comment]
Hey Dominik, thanks for using the package.
Which nuxt version are you using?

**Comment by dritter** [comment]
Ha! I knew I forgot to mention a Version :D

![image](https://user-images.githubusercontent.com/1544760/181033131-ba426bd8-ccd7-4a8b-a12c-5d204acb3f8a.png)

**Comment by JulianMar** [comment]
Ahh you just checked out the project, interesting
You want to improve something? 

But you are right it fails. Very weird, even with node 16
I need to check it in my free time

**Comment by dritter** [comment]
> You want to improve something?

Not yet. ;) TBH, we have a similar error when using `nuxt-bugsnag` in one of our projects, which I wanted to fix:
![image](https://user-images.githubusercontent.com/1544760/181054942-cb30de57-d8a0-4f80-ab02-77db39c7128a.png)

And `plugin.mjs:2` points at:
![image](https://user-images.githubusercontent.com/1544760/181055633-a337c8e9-ee30-4dbe-ba6b-8fa8cd30add2.png)

**Comment by dritter** [comment]
Okay. At least I figured out my problem. I needed to tell vite (in the `nuxt.config.js`) to optimize `@bugsnag/plugin-vue`:
```js
vite: {
    optimizeDeps: {
      include: [
        "@bugsnag/plugin-vue"
      ]
    }
}
```

Source:
https://github.com/vitejs/vite/issues/5566

**Comment by JulianMar** [comment]
Ohhh wow, thanks for finding it out! I will adapt the package to include it 

I will read up on it and release a fix tomorrow or the day after.
