### ISSUE TITLE
Uncaught SyntaxError

### ISSUE THREAD

**Issue by AlissonRA** [JulianMar/nuxt-bugsnag#37]
Hello good afternoon!

I'm having a problem trying to add the module to my project! I get this error in the console when starting the module in nuxt.

`Error: Uncaught SyntaxError: The requested module '/node_modules/@bugsnag/js/browser/notifier.js?v=6b1fff39' does not provide an export named 'default' (at plugin.mjs:1:8)`

I'm using the "3.0.0-rc.8" version of nuxt.

Could anyone help?

**Comment by JulianMar** [comment]
Hey, 

I just created a new release. 
Can you check again? :)

**Comment by AlissonRA** [comment]
It worked out @JulianMar

Thank you for your help! :-)
