### ISSUE TITLE
Compatibility with Nuxt 3 (release candidate)

### ISSUE THREAD

**Issue by pierres** [JulianMar/nuxt-bugsnag#38]
In recent versions of Nuxt 2 (> rc6) nuxt-bugsnag does no longer load and emits the following warning on build:
```
$ nuxi build
Nuxi 3.0.0-rc.9
Nuxt 3.0.0-rc.9 with Nitro 0.5.1
 WARN  Module nuxt-bugsnag is disabled due to incompatibility issues:
 - [nuxt] Nuxt version `^3.0.0 || ^2.16.0` is required but currently using `3.0.0-rc.9`
```

I guess we need to explicitly include the rc versions as it is not covered by `^3.0.0`.

**Comment by JulianMar** [comment]
Hey, I created a new release which should make it work
