### ISSUE TITLE
Vercel Deployment with Source Maps enabled errors out with "No Output Directory named "dist" found after the Build completed"

### ISSUE THREAD

**Issue by zkschmitz** [JulianMar/nuxt-bugsnag#40]
After trying to deploy to Vercel with the Source Maps enabled, I get the following error: 
_Error: No Output Directory named "dist" found after the Build completed. You can configure the Output Directory in your Project Settings._

This only happens when I try and use the "publishRelease" and "baseURL" to upload source maps. If I remove these items, it deployed fine. Everything builds fine, it uploads the source maps to bug snag, but then errors out. 

**Nuxt version: 3.1.2**
**Bugsnag Module Version: 5.9** 

nuxt.config.ts
```
bugsnag: {
		publishRelease: true,
		baseUrl: <URL>,
		config: {
			apiKey: <KEY>,
			enabledReleaseStages: ["staging", "production"],
			releaseStage: process.env.NODE_ENV,
			appVersion: "1.1",
		},
	},
```

Any ideas as to why this might happen?

**Comment by JulianMar** [comment]
Hey, can you try the new version?
[5.9.1](https://www.npmjs.com/package/nuxt-bugsnag/v/5.9.1)

**Comment by zkschmitz** [comment]
@JulianMar - works like a charm! Thanks for the quick fix
