### ISSUE TITLE
Cannot find module 'nuxt-bugsnag-main/dist/module.cjs'. Please verify that the package.json has a valid "main" entry

### ISSUE THREAD

**Issue by vedmant** [JulianMar/nuxt-bugsnag#44]
When I try to run Development, I have following error: `Cannot find module '/Users/vedmant/Downloads/nuxt-bugsnag-main/dist/module.cjs'. Please verify that the package.json has a valid "main" entry`

When I try to run `npm run prepack`, then I have this: `error TS5083: Cannot read file '/Users/vedmant/Downloads/nuxt-bugsnag-main/playground/.nuxt/tsconfig.json'.`

So looks like one requires another one to work, vicious circle.

**Comment by JulianMar** [comment]
Hey, can you try with the newest version? Thank you :)

**Comment by vedmant** [comment]
@JulianMar I downloaded from main branch.

**Comment by JulianMar** [comment]
yeah, i just pushed a new commit

**Comment by vedmant** [comment]
@JulianMar It's the same:

 ERROR  Cannot find module '/Users/vedmant/Downloads/nuxt-bugsnag-main 2/dist/module.cjs'. Please verify that the package.json has a valid "main" entry

**Comment by JulianMar** [comment]
run `dev:prepare` first

**Comment by vedmant** [comment]
@JulianMar Thanks, it works, it was not mentioned in docs.

**Comment by JulianMar** [comment]
Yeah I know, there's currently a issue between nuxt 3.4 and bugsnag - so the repo was in an unstable condition
