### ISSUE TITLE
Error from bugsnag

### ISSUE THREAD

**Issue by madsh93** [JulianMar/nuxt-bugsnag#45]
Hi

I'm currently getting errors in Bugsnag from Bugsnag? I don't really understand this error, maybe you can assist me?

![CleanShot 2023-05-02 at 10 44 14](https://user-images.githubusercontent.com/8860723/235620978-1ab80d38-9fe6-421a-b8d8-ee1153d3cb73.png)

**Comment by JulianMar** [comment]
Hey, sorry but I have no clue what the issue could be. 
Maybe you have the code `e.at(-1)` somewhere in your code?

**Comment by JulianMar** [comment]
Awesome! Thanks for telling me.
