### ISSUE TITLE
As I understand this plugin cannot handle `server` folder, like `defineNitroPlugin` for example?

### ISSUE THREAD

**Issue by vedmant** [JulianMar/nuxt-bugsnag#46]
As I understand this plugin cannot handle `server` folder, like `defineNitroPlugin` for example?

If yes, then what will be recommended way to report exception with this package from `server` folder?

**Comment by JulianMar** [comment]
I haven't used nuxt3 alot yet. I'm not sure how to handle it yet but will think about a way.

**Comment by JulianMar** [comment]
Hey, you can now use `useBugsnag` in the server dir aswell. Thanks for the suggestion! I like this alot.
