### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CareTiger** [JulianMar/nuxt-bugsnag#47]
Hello Julian - 

I am interested in using this module but the documentation is not clear where the options go? do i create a separate config file or do they go into nuxt.config? I tried putting them into nuxt.config and it doesn't work. 

Thanks

**Comment by JulianMar** [comment]
Hey, you can try these settings here. you should just put it in the nuxt.config.ts file
https://github.com/JulianMar/nuxt-bugsnag#config-example

**Comment by JulianMar** [comment]
do you have the module in the module folder?
can you try running `npm run dev`? It should generate the types
Attached is a screenshot of my usage.
![Screenshot 2023-05-11 at 16 18 12](https://github.com/JulianMar/nuxt-bugsnag/assets/29117090/0e89e116-7ccc-4fa0-b359-6038be47d576)

**Comment by CareTiger** [comment]
"dependencies": {
        "@nuxtjs/tailwindcss": "^6.6.8",
        "@storyblok/nuxt": "^5.4.4",
        "nuxt-bugsnag": "^5.9.2",
        "vue-final-modal": "^4.4.2",
        "zod": "^3.21.4"
    }

**Comment by CareTiger** [comment]
modules: [
        [
            '@storyblok/nuxt',
            {
                accessToken: process.env.STORYBLOK_API_TOKEN,
                devtools: true,
                apiOptions: {
                    cache: { type: 'memory' },
                    region: 'us', // region code here
                },
            },
        ],
        '@nuxtjs/tailwindcss',
        '@nuxt/image-edge',
        '@nuxt/devtools',
        '@nuxtjs/supabase',
        'nuxt-icon',
        '@nuxtjs/google-fonts',
        'nuxt-vitest',
        'nuxt-bugsnag',
        // "nuxt-security" // only for SSG apps. we are doing static generation with nitro
    ],

**Comment by CareTiger** [comment]
worked! thank you
