### ISSUE TITLE
Server side error handling bug

### ISSUE THREAD

**Issue by Me-Phew** [JulianMar/nuxt-bugsnag#56]
There seems to be some kind of an issue with handling server side errors. Instead of redirecting to the default Nuxt error page (or a custom one if it is available) a JSON data of the error is rendered. Normally this is only expected to happen when the page is requested with Accept: application/json header as per [Nuxt docs](https://nuxt.com/docs/getting-started/error-handling#rendering-an-error-page).

Here is a [reproduction](https://stackblitz.com/edit/github-zqq3qc?file=app.vue)

And here is an [example of expected behaviour](https://stackblitz.com/edit/github-zqq3qc-okht2s?file=app.vue)

**Comment by JulianMar** [comment]
Hey, seems like this issue was introduced with nuxt 3.6.x. I will check tomorrow with which exact version the issue appeared and will try to fix it.
Thanks for using the library!

**Comment by Me-Phew** [comment]
Alright, thanks!

**Comment by Me-Phew** [comment]
Hi, any progress on this? Maybe you need some help?

**Comment by JulianMar** [comment]
Hey, yeah should be fixed on the main branch. I will release it tomorrow.

I couldnt fix it to keep the same functionality but it will probably added in the future. Right now nuxt does not support handling errors in the h3 server and keeping the same functionality of the error page.

**Comment by Me-Phew** [comment]
That's great, thanks.

**Comment by JulianMar** [comment]
fixed in v7.0.0. Pls reopen if it's still happening :)
