### ISSUE TITLE
App fails if no `apiKey` set

### ISSUE THREAD

**Issue by TiborPL** [JulianMar/nuxt-bugsnag#57]
I was suprised to see the the whole nuxt application fail if `apiKey` is empty.
Normally libraries (sentry) are not loaded/started if there is no key provided.

What's the proper way to handle this?

**Comment by JulianMar** [comment]
Hey, you can disable the module by setting the `disable: true` option in the bugsnag configuration. 
I will change the behaviour of the application so it's a bit more expected.

**Comment by TiborPL** [comment]
@JulianMar thank you for the swift reply, it did help. :)
Don't know about others, but it might help to include `disabled` module config property into the docs too.

Also, it's interesting that bugsnag dies with fatal error if there's no `APIKey`. Normally libraries just don't start and give a warning in console, like Sentry.
Maybe you can add this graceful failing to the module something like this:

```javascript
if (!options.config.apiKey) {
  console.warn('[bugsnag] apiKey not defined. Plugin is not loaded.')
  return
}
```
