### ISSUE TITLE
What do you think about lazyloading the script?

### ISSUE THREAD

**Issue by Youhan** [JulianMar/nuxt-bugsnag#63]
Using `npx nuxi analyze .   ` it looks like that the bugsnag js ends up in the main js file. This could be the desired behaviour. I think there needs to be a way to lazyload the js. Sometime I would be willing to sacrifice some of the errors for better performance scores. (penalty for unused javascript)

**Comment by JulianMar** [comment]
Hey, right now I am not thinking about this feature. It will create a lot of overhead. Most probably you have the `useBugsnag`  method on almost every page. So it will result in the same behaviour. 
But I'm open for this improvement, and some performance differences.
