### ISSUE TITLE
Identify users

### ISSUE THREAD

**Issue by Youhan** [JulianMar/nuxt-bugsnag#64]
On the docs, it looks like it is possible to identify users by adding it to the sent event like this

```
Bugsnag.start({
  onError: function (event) {
    event.setUser('3', 'bugs.nag@bugsnag.com', 'Bugs Nag')
  }
})
```
Would it be possible to do it with the module? 

My `user` is a reactive `useState` ref that is null initially but may get populated if the user signs in.

**Comment by Youhan** [comment]
Just to clarify, it is possible to setUser while using the `.notify` method. But that's only for handled errors.

**Comment by JulianMar** [comment]
Hey, you can use the second method from the bugsnag docs.
https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#adding-user-data

```js
useBugsnag().setUser('3', 'bugs.nag@bugsnag.com', 'Bugs Nag')
```
