### ISSUE TITLE
Nuxt 3.9

### ISSUE THREAD

**Issue by marwenbk** [JulianMar/nuxt-bugsnag#68]
i tried the plugin with Nuxt 3.9 
i followed the instruction 
when i run pnpm dev i get 
 ERROR  [worker reload] [worker init] Cannot find module '/nuxt-bugsnag@7.2.1/node_modules/nuxt-bugsnag/dist/runtime/server/plugins/bugsnag.ts' imported from /Users/marwen/Desktop/makhbazti-nuxt/.nuxt/dev/index.mjs

**Comment by JulianMar** [comment]
Sorry, the new Version should fix it.
