### ISSUE TITLE
Cannot deploy to cloudflare pages

### ISSUE THREAD

**Issue by carlosvaldesweb** [JulianMar/nuxt-bugsnag#75]
Hello, if i try to deploy to cloudflare pages i get:
```

18:23:01.311 | Success: Assets published!
-- | --
18:23:02.431 | Error: Failed to publish your Function. Got error: Uncaught TypeError: Cannot read properties of undefined (reading 'toString')   at chunks/runtime.mjs:1:193088   at chunks/runtime.mjs:1:216534
```

# Reproduction
https://stackblitz.com/edit/nuxt-starter-xe6td5?file=nuxt.config.ts

Also i've opened a issue in nixt, but i've closed because i found that it's an issue with bugsnag.
https://github.com/nuxt/nuxt/issues/27605

**Comment by JulianMar** [comment]
Hey,
if looks like it might be a issue with bugsnag overall. Here is a Issue about it.
I will check if we can maybe do a workaround to fix this.
https://github.com/bugsnag/bugsnag-js/issues/637
