### ISSUE TITLE
How to enable only for production / staging server?

### ISSUE THREAD

**Issue by simplenotezy** [JulianMar/nuxt-bugsnag#9]
I am not sure how I disable this locally. Currently I have:

    notifyReleaseStages: ['staging', 'production']

However, where / how do I define what the current release stage is?

**Comment by JulianMar** [comment]
Hi you can use:
```
releaseStage: Settings.env.environment,
```
replacing the environement with you env :)

Ohh and btw. the `notifyReleaseStages` got changed to `enabledReleaseStages`

**Comment by simplenotezy** [comment]
@JulianMar So like this?

`nuxt.config.js`

		[ 'nuxt-bugsnag', {
			apiKey: '1234',
			reporterOptions: {
				releaseStage: process.env.ENVIRONMENT || 'local',
				autoAssignRelease: true
			},
			publishRelease: (process.env.ENVIRONMENT !== 'local'),
			notifyReleaseStages: [ 'staging', 'production' ],
			enabledReleaseStages: [ 'staging', 'production' ]
		} ],

**Comment by JulianMar** [comment]
this is how I use it:

```javascript
[
      'nuxt-bugsnag',
      {
        apiKey: Settings.env.bugsnag_key,
        config: {
          enabledReleaseStages: ['production', 'dev'],
          releaseStage: Settings.env.environment,
          appVersion: Settings.env.version
        },
        publishRelease: Settings.env.environment === 'production'
      }
]

```
